// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create a new conversation
 */
export function CreateConversation(input: $models.CreateConversationRequest): $CancellablePromise<$models.ConversationResponse> {
    return $Call.ByID(2832442755, input);
}

/**
 * Deletes a conversation
 */
export function DeleteConversation(input: $models.DeleteConversationRequest): $CancellablePromise<void> {
    return $Call.ByID(2681103028, input);
}

/**
 * Lists conversations
 */
export function ListConversations(): $CancellablePromise<$models.ConversationResponse[] | null> {
    return $Call.ByID(1369374740);
}
