// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ConversationResponse {
    "id": string;
    "name": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface CreateConversationRequest {
    "name": string;
}
