// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum MessageType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Indicates a message sent by user
     */
    MessageTypeUser = "user",

    /**
     * Indicates a message sent by llm
     */
    MessageTypeLLM = "llm",
};
