// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ProviderInput {
    "name": string;
    "providerType": string;
    "baseUrl": string | null;
    "apiKey": string | null;
}

export interface ProviderResponse {
    "id": string;
    "name": string;
    "providerType": string;
    "baseUrl": string | null;
    "apiKey": string | null;
    "createdAt": string;
    "updatedAt": string;
}
