// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error: Unused imports
import {
	Call as $Call,
	type CancellablePromise as $CancellablePromise,
} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error: Unused imports
import type * as $models from "./models.js";

export function CreateProvider(
	input: $models.ProviderInput,
): $CancellablePromise<$models.ProviderResponse> {
	return $Call.ByID(4186712969, input);
}

export function DeleteProvider(id: string): $CancellablePromise<void> {
	return $Call.ByID(776750002, id);
}

export function GetProvider(
	id: string,
): $CancellablePromise<$models.ProviderResponse> {
	return $Call.ByID(977840529, id);
}

export function ListProviders(): $CancellablePromise<
	$models.ProviderResponse[] | null
> {
	return $Call.ByID(1706810602);
}

export function UpdateProvider(
	id: string,
	input: $models.ProviderInput,
): $CancellablePromise<$models.ProviderResponse> {
	return $Call.ByID(2978561824, id, input);
}
