// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateProvider(input: $models.ProviderInput): $CancellablePromise<$models.ProviderResponse> {
    return $Call.ByID(1841495485, input);
}

export function DeleteProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(4291218382, id);
}

export function GetProvider(id: string): $CancellablePromise<$models.ProviderResponse> {
    return $Call.ByID(2555477485, id);
}

export function ListProviders(): $CancellablePromise<$models.ProviderResponse[] | null> {
    return $Call.ByID(990855086);
}
