set default-list := true


# Run code generation and build the app
build:
    sqlc generate
    wails3 build

# Run all linters and type checkers
check: _check-frontend _check-go

# Run code generation and start dev server
dev:
    sqlc generate
    wails3 dev

# Format all source code
fmt: _fmt-frontend _fmt-go

# Generate sqlc & wails bindings
gen:
    sqlc generate
    wails3 generate bindings

# Run all tests
test: _test-frontend _test-go

[working-directory: 'frontend']
_check-frontend:
    npm run check

[working-directory: 'frontend']
_fmt-frontend:
    npm run check -- --write

[working-directory: 'frontend']
_test-frontend:
    npm run test -- --run

_check-go:
    go vet ./...

_fmt-go:
    go fmt ./...

_test-go:
    go test ./...
