// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: conversations.sql

package local_store

import (
	"context"
	"time"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (
    id,
    name,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?
) RETURNING id, name, created_at, updated_at
`

type CreateConversationParams struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, name, created_at, updated_at FROM conversations ORDER BY updated_at DESC
`

func (q *Queries) ListConversations(ctx context.Context) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationUpdatedAt = `-- name: UpdateConversationUpdatedAt :exec
UPDATE conversations SET updated_at = ? WHERE id = ?
`

type UpdateConversationUpdatedAtParams struct {
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateConversationUpdatedAt(ctx context.Context, arg UpdateConversationUpdatedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateConversationUpdatedAt, arg.UpdatedAt, arg.ID)
	return err
}
