// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package local_store

import (
	"database/sql"
	"time"
)

type Conversation struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Message struct {
	ID             string
	ConversationID string
	Body           string
	MessageType    string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Provider struct {
	ID           string
	Name         string
	ProviderType string
	BaseUrl      sql.NullString
	ApiKey       sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
