// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package local_store

import (
	"database/sql"
)

type Provider struct {
	ID           string
	Name         string
	ProviderType string
	BaseUrl      sql.NullString
	ApiKey       sql.NullString
	CreatedAt    int64
	UpdatedAt    int64
}
