// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: providers.sql

package local_store

import (
	"context"
	"database/sql"
	"time"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (
    id,
    name,
    provider_type,
    base_url,
    api_key,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
) RETURNING id, name, provider_type, base_url, api_key, created_at, updated_at
`

type CreateProviderParams struct {
	ID           string
	Name         string
	ProviderType string
	BaseUrl      sql.NullString
	ApiKey       sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRowContext(ctx, createProvider,
		arg.ID,
		arg.Name,
		arg.ProviderType,
		arg.BaseUrl,
		arg.ApiKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.BaseUrl,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM providers WHERE id = ?
`

func (q *Queries) DeleteProvider(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProvider, id)
	return err
}

const getProvider = `-- name: GetProvider :one
SELECT id, name, provider_type, base_url, api_key, created_at, updated_at FROM providers WHERE id = ?
`

func (q *Queries) GetProvider(ctx context.Context, id string) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.BaseUrl,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, provider_type, base_url, api_key, created_at, updated_at FROM providers ORDER BY created_at DESC
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.QueryContext(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProviderType,
			&i.BaseUrl,
			&i.ApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers SET
    name = ?,
    provider_type = ?,
    base_url = ?,
    api_key = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, name, provider_type, base_url, api_key, created_at, updated_at
`

type UpdateProviderParams struct {
	Name         string
	ProviderType string
	BaseUrl      sql.NullString
	ApiKey       sql.NullString
	UpdatedAt    time.Time
	ID           string
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRowContext(ctx, updateProvider,
		arg.Name,
		arg.ProviderType,
		arg.BaseUrl,
		arg.ApiKey,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.BaseUrl,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
