// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create a new message in the given conversation
 */
export function CreateMessage(input: $models.CreateMessageRequest): $CancellablePromise<$models.MessageResponse> {
    return $Call.ByID(3696102705, input);
}

/**
 * Lists messages for a given conversation
 */
export function ListMessagesByConversation(input: $models.ListMessagesByConversationRequest): $CancellablePromise<$models.MessageResponse[] | null> {
    return $Call.ByID(4092714032, input);
}
