// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

export interface CreateMessageRequest {
    /**
     * Conversation ID message belongs to
     */
    "conversationId": string;

    /**
     * Body of message
     */
    "body": string;
}

export interface ListMessagesByConversationRequest {
    /**
     * Conversation ID message belongs to
     */
    "conversationId": string;
}

export interface MessageResponse {
    /**
     * Message ID
     */
    "id": string;

    /**
     * Conversation ID message belongs to
     */
    "conversationId": string;

    /**
     * Body of message
     */
    "body": string;

    /**
     * Type of message ('user' | 'llm')
     */
    "messageType": storage$0.MessageType;

    /**
     * When the message was created
     */
    "createdAt": string;

    /**
     * When the message was updated
     */
    "updatedAt": string;
}
